/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.csvmanl.parser.antlr.internal.InternalCsvManParser;
import org.xtext.example.csvmanl.services.CsvManGrammarAccess;

public class CsvManParser extends AbstractAntlrParser {

	@Inject
	private CsvManGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCsvManParser createParser(XtextTokenStream stream) {
		return new InternalCsvManParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public CsvManGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CsvManGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
