/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.csvman.ui.internal.CsvmanActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CsvManExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CsvmanActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CsvmanActivator.getInstance().getInjector(CsvmanActivator.ORG_XTEXT_EXAMPLE_CSVMANL_CSVMAN);
	}
	
}
