/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.validation;

import org.xtext.example.csvmanl.validation.AbstractCsvManValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CsvManValidator extends AbstractCsvManValidator {
}
