/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.csvman.ui.internal.CsvmanActivator;

public class CsvManUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CsvmanActivator.getInstance().getInjector("org.xtext.example.csvmanl.CsvMan");
	}

}
