/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.csvmanl.CsvManRuntimeModule;
import org.xtext.example.csvmanl.CsvManStandaloneSetup;
import org.xtext.example.csvmanl.ide.CsvManIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CsvManIdeSetup extends CsvManStandaloneSetup {
  @Override
  public Injector createInjector() {
    CsvManRuntimeModule _csvManRuntimeModule = new CsvManRuntimeModule();
    CsvManIdeModule _csvManIdeModule = new CsvManIdeModule();
    return Guice.createInjector(Modules2.mixin(_csvManRuntimeModule, _csvManIdeModule));
  }
}
