/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.ide;

import org.xtext.example.csvmanl.ide.AbstractCsvManIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CsvManIdeModule extends AbstractCsvManIdeModule {
}
