<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="csvManager" nsURI="http://www.example.org/csvManager" nsPrefix="csvManager">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyword" lowerBound="1"
        eType="#//Keyword" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionParameter" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionParameter" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Load" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Show" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Update" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="#//Keyword"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Where" eSuperTypes="#//Condition"/>
</ecore:EPackage>
