/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl;

import org.xtext.example.csvmanl.AbstractCsvManRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CsvManRuntimeModule extends AbstractCsvManRuntimeModule {
}
