/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl;

import org.xtext.example.csvmanl.CsvManStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CsvManStandaloneSetup extends CsvManStandaloneSetupGenerated {
  public static void doSetup() {
    new CsvManStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
