/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CsvManStandaloneSetup /* implements CsvManStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type CsvManStandaloneSetup");
  }
}
