/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.csvmanl.ui.AbstractCsvManUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CsvManUiModule extends AbstractCsvManUiModule {
  public CsvManUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
