/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.csvmanl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CsvManStandaloneSetup extends CsvManStandaloneSetupGenerated {

	def static void doSetup() {
		new CsvManStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
